In [156]:
import numpy as np
import pandas as pd

In [157]:
sales = [0, 5, 155, 0, 518, 9, 1827, 616, 317, 325]
sales_series = pd.Series(sales, name='Sales')
sales_series

0       0
1       5
2     155
3       0
4     518
5       9
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

## Panda Series properties:
- values
- index
- name
- dtype

In [158]:
sales_series.values

array([   0,    5,  155,    0,  518,    9, 1827,  616,  317,  325])

In [159]:
sales_series.index

RangeIndex(start=0, stop=10, step=1)

In [160]:
sales_series.name

'Sales'

In [161]:
sales_series.dtype

dtype('int64')

In [162]:
sales_series.astype('bool')

0    False
1     True
2     True
3    False
4     True
5     True
6     True
7     True
8     True
9     True
Name: Sales, dtype: bool

In [163]:
sales_series.astype('float')

0       0.0
1       5.0
2     155.0
3       0.0
4     518.0
5       9.0
6    1827.0
7     616.0
8     317.0
9     325.0
Name: Sales, dtype: float64

In [146]:
# create a Dataframe from the oil file, drop missing values
oil = pd.read_csv('./oil.csv').dropna()
# pd.to_csv

# Grab 100 rows of oil prices
oil_array = np.array(oil['dcoilwtico'].iloc[1000:1100])

oil_array

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

In [147]:
# convert oil_array to a series

oil_series = pd.Series(oil_array, name = 'oil_prieces')
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...  
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: oil_prieces, Length: 100, dtype: float64

In [7]:
oil_series.name

'oil_prieces'

In [8]:
oil_series.mean()

51.128299999999996

In [9]:
oil_series.astype('int').mean()

50.66

In [11]:
oil_series.astype('int')

0     52
1     51
2     51
3     52
4     52
      ..
95    45
96    47
97    47
98    47
99    48
Name: oil_prieces, Length: 100, dtype: int64

In [13]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       9
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [14]:
sales_series[2]

155

In [15]:
sales_series[2:4]

2    155
3      0
Name: Sales, dtype: int64

In [22]:
items = ['coffee', 'bananas', 'tea', 'coconut', 'sugar']
sales_items = sales_series[:5]
sales_items

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [25]:
# pd_sales = pd.Series(sales_items_list, index=items, name = 'Sales_Item')
sales_items.index = items
sales_items

coffee       0
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [26]:
sales_items['tea']

155

In [27]:
sales_items['bananas':'coconut']

bananas      5
tea        155
coconut      0
Name: Sales, dtype: int64

# ILOC METHOD
.iloc method - access values by their positional index

#### df.iloc[row position, column position]

In [28]:
sales_items.iloc[2]

155

In [30]:
sales_items.iloc[3:5]

coconut      0
sugar      518
Name: Sales, dtype: int64

In [31]:
sales_items.loc['tea']

155

In [32]:
sales_items.loc['bananas':'sugar']

bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

### DUPLICATE INDEX VALUES

In [33]:
items = ['coffee', 'coffee', 'tea', 'coconut', 'sugar']

In [34]:
sales_items.index = items
sales_items

coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [35]:
sales_items.loc['coffee']

coffee    0
coffee    5
Name: Sales, dtype: int64

### RESETTING THE INDEX

In [36]:
sales_items.reset_index()

index  Sales
0   coffee      0
1   coffee      5
2      tea    155
3  coconut      0
4    sugar    518

In [37]:
sales_items.reset_index(drop=True)

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [91]:
oil

date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

# Assignment 2: Accessing Series Data
Set the date series, which has been created below, to be the index of the oil price series created in assignment 1.

Then, take the mean of the first 10 and last 10 prices of the series.

Finally, grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.
### create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("./oil.csv").dropna()
oil

In [148]:
oil_dates = pd.Series(oil['date'].iloc[1000:1100])
oil_dates

1035    2016-12-20
1036    2016-12-21
1037    2016-12-22
1038    2016-12-23
1040    2016-12-27
           ...    
1135    2017-05-09
1136    2017-05-10
1137    2017-05-11
1138    2017-05-12
1139    2017-05-15
Name: date, Length: 100, dtype: object

In [149]:
oil_series.index = oil_dates
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil_prieces, Length: 100, dtype: float64

In [55]:
oil_series.iloc[:10].mean()

52.765

In [57]:
oil_series.iloc[-10:].mean()

47.13

In [58]:
oil_selection = oil_series.loc['2017-01-01':'2017-01-07']
oil_selection

date
2017-01-03    52.36
2017-01-04    53.26
2017-01-05    53.77
2017-01-06    53.98
Name: oil_prieces, dtype: float64

In [59]:
oil_selection.reset_index(drop=True)

0    52.36
1    53.26
2    53.77
3    53.98
Name: oil_prieces, dtype: float64

### FILTERING SERIES

In [62]:
sales_series = sales_series[:5]
sales_series

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [63]:
sales_series.loc[sales_series > 0 ]

1      5
2    155
4    518
Name: Sales, dtype: int64

In [64]:
sales_series > 0

0    False
1     True
2     True
3    False
4     True
Name: Sales, dtype: bool

In [67]:
sales_series.index = items
mask = (sales_series > 0) & (sales_series.index == 'coffee')
sales_series.loc[mask]

coffee    5
Name: Sales, dtype: int64

In [68]:
sales_series == 5

coffee     False
coffee      True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [69]:
sales_series.eq(5)

coffee     False
coffee      True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [70]:
sales_series.index.isin(['coffee','tea'])

array([ True,  True,  True, False, False])

## SORTING SERIES

sales_series.sort_values(ascending=False)

In [74]:
sales_series.sort_index(ascending=True)

coconut      0
coffee       0
coffee       5
sugar      518
tea        155
Name: Sales, dtype: int64

# Assignment 3: Sorting and Filtering Series

* First, get the 10 lowest prices from the data. 
* Sort the 10 lowest prices by date, starting with the most recent and ending with the oldest price.

* Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.
### list of dates to be used to solve bullet 3

dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-06",
    "2017-03-05",
    "2017-02-12",
    "2017-03-21",
    "2017-04-14",
    "2017-04-15",
]

In [80]:
oil_sorted = oil_series.sort_values(ascending=True).iloc[:10]
oil_sorted

date
2017-05-04    45.55
2017-05-09    45.84
2017-05-05    46.23
2017-05-08    46.46
2017-03-23    47.00
2017-03-21    47.02
2017-03-27    47.02
2017-03-14    47.24
2017-05-10    47.28
2017-03-22    47.29
Name: oil_prieces, dtype: float64

In [84]:
oil_sorted = oil_sorted.sort_index(ascending=False)
oil_sorted

date
2017-05-10    47.28
2017-05-09    45.84
2017-05-08    46.46
2017-05-05    46.23
2017-05-04    45.55
2017-03-27    47.02
2017-03-23    47.00
2017-03-22    47.29
2017-03-21    47.02
2017-03-14    47.24
Name: oil_prieces, dtype: float64

In [92]:
dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-06",
    "2017-03-05",
    "2017-02-12",
    "2017-03-21",
    "2017-04-14",
    "2017-04-15",
]
mask = (oil_sorted < 50) & (oil_sorted.index.isin(dates))
oil_sorted.loc[mask]

date
2017-03-21    47.02
Name: oil_prieces, dtype: float64

## Arithmetic operators and methods

In [93]:
sales_series + 2

coffee       2
coffee       7
tea        157
coconut      2
sugar      520
Name: Sales, dtype: int64

In [94]:
sales_series.add(2)

coffee       2
coffee       7
tea        157
coconut      2
sugar      520
Name: Sales, dtype: int64

In [95]:
sales_series.mul(2)

coffee        0
coffee       10
tea         310
coconut       0
sugar      1036
Name: Sales, dtype: int64

In [97]:
dollar_sales_series = '$' + sales_series.astype('string')
dollar_sales_series

coffee       $0
coffee       $5
tea        $155
coconut      $0
sugar      $518
Name: Sales, dtype: string

In [99]:
dollar_sales_series.str.strip('$').astype('float')

coffee       0.0
coffee       5.0
tea        155.0
coconut      0.0
sugar      518.0
Name: Sales, dtype: float64

# Assignment 4: Series Operations

* Increase the prices in the oil series by 10%, and add an additional 2 dollars per barrel on top of that.

* Then, create a series that represents the difference between each price and max price.

* Finally, extract the month from the string dates in the index and store them as an integer in their own series.

In [110]:
oil_increased = oil_series * 1.1 + 2
oil_increased

date
2016-12-20    59.442
2016-12-21    58.584
2016-12-22    59.178
2016-12-23    59.211
2016-12-27    60.102
               ...  
2017-05-09    52.424
2017-05-10    54.008
2017-05-11    54.591
2017-05-12    54.613
2017-05-15    55.746
Name: oil_prieces, Length: 100, dtype: float64

In [111]:
max_price = oil_increased.max()
max_price

61.928000000000004

In [113]:
oil_diff = (oil_increased - max_price) / max_price
oil_diff

date
2016-12-20   -0.040143
2016-12-21   -0.053998
2016-12-22   -0.044406
2016-12-23   -0.043874
2016-12-27   -0.029486
                ...   
2017-05-09   -0.153469
2017-05-10   -0.127890
2017-05-11   -0.118476
2017-05-12   -0.118121
2017-05-15   -0.099826
Name: oil_prieces, Length: 100, dtype: float64

In [133]:
dates = pd.Series(oil_series.index)
dates

0     2016-12-20
1     2016-12-21
2     2016-12-22
3     2016-12-23
4     2016-12-27
         ...    
95    2017-05-09
96    2017-05-10
97    2017-05-11
98    2017-05-12
99    2017-05-15
Name: date, Length: 100, dtype: object

In [134]:
months = dates.str[5:7].astype('int')
months

0     12
1     12
2     12
3     12
4     12
      ..
95     5
96     5
97     5
98     5
99     5
Name: date, Length: 100, dtype: int64

## NUMERIC SERIES AGGREGATION

In [117]:
oil_series.sum()

5112.83

In [118]:
sales_series.sum()

678

In [119]:
sales_series.loc['coffee'].sum()

5

In [120]:
sales_series.mean()

135.6

In [121]:
sales_series.std()

223.8510665598893

# CATEGORICAL SERIES AGGREGATION

In [122]:
sales_series

coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [123]:
sales_series.unique()

array([  0,   5, 155, 518])

In [124]:
sales_series.nunique()

4

In [137]:
oil_increased.index = months
oil_increased

date
12    59.442
12    58.584
12    59.178
12    59.211
12    60.102
       ...  
5     52.424
5     54.008
5     54.591
5     54.613
5     55.746
Name: oil_prieces, Length: 100, dtype: float64

In [140]:
oil_increased.loc[3].sum()

1293.994

In [151]:
oil_increased.loc[1].count()

20

In [150]:
oil_increased.loc[2].count()

19

In [152]:
oil_increased.astype('int').value_counts(normalize=True)

oil_prieces
60    0.22
59    0.19
61    0.14
54    0.10
55    0.09
58    0.06
57    0.06
56    0.06
53    0.05
52    0.03
Name: proportion, dtype: float64

## MISSING DATA

In [165]:
sales = [0, 5, 155, np.nan, 518]
my_sales = pd.Series(sales)
my_sales

0      0.0
1      5.0
2    155.0
3      NaN
4    518.0
dtype: float64

In [167]:
my_sales.add(2, fill_value=0)

0      2.0
1      7.0
2    157.0
3      2.0
4    520.0
dtype: float64

### Pandas released its own missing data type NA in 2020

In [177]:
sales = [0, 5, 155, pd.NA, 518]
my_sales = pd.Series(sales, dtype='Int16')
my_sales

0       0
1       5
2     155
3    <NA>
4     518
dtype: Int16

In [178]:
my_sales.isna()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [171]:
my_sales.isna().sum()

1

In [184]:
my_sales.value_counts()

0      1
5      1
155    1
518    1
Name: count, dtype: Int64

In [179]:
my_sales.value_counts(dropna=False)

0       1
5       1
155     1
518     1
<NA>    1
Name: count, dtype: Int64

In [174]:
my_sales.dropna()

0      0
1      5
2    155
4    518
dtype: Int16

In [180]:
my_sales.fillna(10)

0      0
1      5
2    155
3     10
4    518
dtype: Int16

In [185]:
my_sales.astype('float').fillna(my_sales.mean())

0      0.0
1      5.0
2    155.0
3    169.5
4    518.0
dtype: float64

In [186]:
oil_series.isna().count()

100

In [187]:
oil_series.fillna(oil_series.median())

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil_prieces, Length: 100, dtype: float64

## Apply method

In [188]:
clean_wholesale = pd.Series([3.99, 5.99, 22.99, 7.99, 33.99])
clean_wholesale

0     3.99
1     5.99
2    22.99
3     7.99
4    33.99
dtype: float64

In [191]:
def discount(price):
    if price > 10:
        return round(price * 0.9, 2)
    return price

In [192]:
clean_wholesale.apply(discount)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [194]:
# .where(logical test, value if false, inplace=False)
clean_wholesale.where(clean_wholesale <= 20, round(clean_wholesale * 0.9, 2), inplace=False)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [195]:
clean_wholesale.where(~(clean_wholesale > 20), round(clean_wholesale * 0.9, 2), inplace=False)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [196]:
(
    clean_wholesale
    .where(~(clean_wholesale > 20), round(clean_wholesale * 0.9, 2), inplace=False)
    .where((clean_wholesale > 10), 0)
)

0     0.00
1     0.00
2    20.69
3     0.00
4    30.59
dtype: float64