# Exercise 1:

1. Import the numpy package under the name np.

In [3]:
import numpy as np

2. Create a vector* of zeros with size 10 using np.zeros().

In [5]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Compute the memory size* of any array. Note: You can do this by multiplying the length of the array by the size of one array element, which you can find using the .itemsize attribute.

In [7]:
zeros.size * zeros.itemsize

80

4. Retrieve the documentation of the numpy add function from the command line.

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

5. Create a vector with values ranging from 10 to 49 using np.arange().

In [17]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

6. Reverse a vector so the first element becomes last (Hint: Use slicing).

In [18]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

7. Create a 3x3 matrix* with values ranging from 0 to 8 using np.reshape().

np.arange(0,9).reshape(3,3)

8. Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero().

In [20]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

9. Create a 3x3 identity matrix* using np.eye().

In [21]:
np.eye(3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

10. Create a 5x5 matrix with row values ranging from 0 to 4. The output should be a matrix where each row is [0, 1, 2, 3, 4].

In [27]:
row = np.arange(0,5)
np.tile(row, (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

11. Create a vector of size 10 with values ranging from 0 to 1, both excluded. You can use np.linspace.

In [28]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

12. Create a random vector of size 10 and sort it.

In [29]:
np.sort(np.random.rand(10))

array([0.09839513, 0.11777566, 0.21347171, 0.29276536, 0.32690422,
       0.37193345, 0.47089187, 0.56147533, 0.79273175, 0.84957074])

13. Print the minimum and maximum representable value for each numpy scalar type* (int8, int32, int64, float32, float64). Use np.iinfo and np.finfo.

np.iinfo(np.int8).min

In [34]:
np.iinfo(np.int8).max

127

In [35]:
np.iinfo(np.int32).min

-2147483648

In [36]:
np.iinfo(np.int32).max

2147483647

In [37]:
np.iinfo(np.int64).min

-9223372036854775808

In [38]:
np.iinfo(np.int64).max

9223372036854775807

In [39]:
np.finfo(np.float32).min

-3.4028235e+38

In [40]:
np.finfo(np.float32).max

3.4028235e+38

In [41]:
np.finfo(np.float64).min

-1.7976931348623157e+308

In [42]:
np.finfo(np.float64).max

1.7976931348623157e+308

14. How to convert a float (32 bits) array into an integer (32 bits) in place? Use np.ndarray.astype.

In [44]:
np.array([1.28, 2.35780, 2.8]).astype(int)

array([1, 2, 2])

15. Subtract the mean* of each row of a matrix. Use np.mean with axis=1.

In [46]:
mymatrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mymatrix - np.mean(mymatrix, axis=1)

array([[-1., -3., -5.],
       [ 2.,  0., -2.],
       [ 5.,  3.,  1.]])

16. How to sort an array by the nth column? Use np.argsort.

In [54]:
mysort = np.array([[0, 5, 3], [2, 2, 1], [4, 6, 2]])
mysort[mysort[:,2].argsort()]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

17. How to swap two rows of an array? You can do this using array indexing.

In [56]:
myswap = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
myswap[[0,1]] = myswap[[1,0]]
myswap

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

18. Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.

In [62]:
c = np.array([2,3,1])
b = np.array([0,1,2])
a = np.repeat(b, c)
a

array([0, 0, 1, 1, 1, 2])

In [63]:
np.bincount(a)

array([2, 3, 1])