In [2]:
import numpy as np

In [2]:
my_list = [x * 10 for x in range(1,11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [3]:
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
my_2d_array = my_array.reshape(2,5)
my_2d_array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [14]:
ones = np.ones((10,10), dtype=int)
ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
ones.dtype

dtype('float64')

In [13]:
zeros = np.zeros((5,5), dtype=int)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
myrange = np.arange(10)
myrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_linspace = np.linspace(0,100, 5)
my_linspace

array([  0.,  25.,  50.,  75., 100.])

In [3]:
np.arange(1,9,2).reshape(2,2)

array([[1, 3],
       [5, 7]])

### np.default_rng(seed) - random number generator
### default_rng.random(n)
### default_rng.normal(mean, stdev, n)

In [10]:
rng = np.random.default_rng(123456)
random_array = rng.random(10)
random_array

array([0.63651375, 0.38481166, 0.04744542, 0.95525274, 0.90605094,
       0.45696955, 0.28053348, 0.6361488 , 0.98071069, 0.81243179])

In [23]:
random_normal = rng.normal(5, 1, 10)
random_normal

array([6.10047658, 5.61305867, 4.56283806, 6.24196053, 3.38821608,
       4.68299094, 4.31826182, 5.65299213, 4.75560389, 3.88640651])

In [4]:
new_array = np.arange(10, 101, 10).reshape(5,2)
new_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [5]:
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

### Indexing & slicing 1d arrays - same as base python

In [4]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
integer_array[4]

4

In [45]:
integer_array[-2]

10

In [46]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [5]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
new_array[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
new_array[:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [9]:
new_array[2, 1]

9

In [7]:
sales_array = np.array([[0, 5, 155, 0, 518],[9,1827, 616, 317, 325]])
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [8]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [  11, 1829,  618,  319,  327]])

In [9]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [10]:
price = sales_array[1, :]
price

array([   9, 1827,  616,  317,  325])

In [11]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

In [14]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [23]:
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [15]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [16]:
discount_pct = random_array[:2].reshape(6)
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [17]:
pct_owed = 1 - discount_pct
pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [18]:
final_owed = total * pct_owed
final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

## FILTERING ARRAYS
- you can filter arrays by indexing them with a logical test

In [39]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [40]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [41]:
sales_array[sales_array != 0]

array([   5,  155,  518,    9, 1827,  616,  317,  325])

In [42]:
sales_array[(sales_array>100) & (sales_array<500)]

array([155, 317, 325])

In [43]:
mask = (sales_array>100) & (sales_array<500)
sales_array[mask]

array([155, 317, 325])

In [45]:
product_array = np.array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [47]:
sales_array = sales_array[0, :]
sales_array

array([  0,   5, 155,   0, 518])

In [48]:
product_array[sales_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

In [49]:
sales_array[1] = 25
sales_array

array([  0,  25, 155,   0, 518])

In [50]:
sales_array[sales_array == 0] = 5
sales_array

array([  5,  25, 155,   5, 518])

In [51]:
inventory_array = np.array([12,102,18,0,0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [52]:
np.where(inventory_array <= 0, 'Out of stock', 'In stock')

array(['In stock', 'In stock', 'In stock', 'Out of stock', 'Out of stock'],
      dtype='<U12')

In [53]:
np.where(inventory_array <= 0, 'Out of stock', product_array)

array(['fruits', 'vegetables', 'cereal', 'Out of stock', 'Out of stock'],
      dtype='<U12')

In [55]:
sales = [0, 5, 155, 0, 518, 9, 1827, 616, 317, 325]
sales_array = np.array(sales).reshape(2,5)
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [56]:
sales_array.sum()

3772

In [57]:
sales_array.mean()

377.2

In [58]:
sales_array.max()

1827

In [59]:
sales_array.min()

0

In [60]:
sales_array.sum(axis=0)

array([   9, 1832,  771,  317,  843])

In [61]:
sales_array.sum(axis=1)

array([ 678, 3094])

In [62]:
np.median(sales_array)

236.0

In [63]:
np.percentile(sales_array,90)

737.0999999999996

In [64]:
np.unique(sales_array)

array([   0,    5,    9,  155,  317,  325,  518,  616, 1827])

In [65]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 3.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [ ]:
def for_loop_multiply_list(list1, list2):
    product_list = []
    for element1, element2 in zip(list1, list2):
        product_list.append(element1 * element2)
    return product_list

def multiply_arrays(array1, array2):
    return array1 * array2

In [ ]:
list1 = list(range(1000))
list2 = list(range(1000))